### ISSUE TITLE
Should we be using .Rmd or .md files?

### ISSUE THREAD

**Issue by joshuarcarter** [shellstanton/accessibility#2]
I'm currently updating/adding to .Rmd and changes don't propagate through to the .md files (why would they, ha?). Moving forward should we stick to .Rmd or just .md?

If .Rmd, we should remove .md from the repo :)

**Comment by joshuarcarter** [comment]
.md files are updated when the .Rmd is successfully knit, so I suppose this isn't too much of an issue with regards to version control if both files feature in the commit. Just potentially confusing. Any thoughts?

**Comment by shellstanton** [comment]
I was following this https://happygitwithr.com/rmd-test-drive.html , and it suggested that as the .Rmd file in github doesn't display the output within in that .md was the more reliable one to use. I set it up so both are generated, and assuming this doesn't cause any problems then we may as well stick with generating both I think.

**Comment by joshuarcarter** [comment]
Okay, sounds good to me :)
